openapi: 3.0.0
info:
  title: Demo
  description: Demo
  version: 1.0.0.0
servers:
- url: /
paths:
  /getAll:
    get:
      tags:
      - Character
      description: Get Character List
      operationId: get_character_list
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CharacterList'
      x-openapi-router-controller: swagger_server.controllers.character_controller
  /get/{id}:
    get:
      tags:
      - Character
      description: Get Character By Id
      operationId: get_character_by_id
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
      x-openapi-router-controller: swagger_server.controllers.character_controller
  /add:
    post:
      tags:
      - Character
      description: Add Character
      operationId: add_character
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Character'
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
      x-openapi-router-controller: swagger_server.controllers.character_controller
  /delete/{id}:
    delete:
      tags:
      - Character
      description: Delete Character
      operationId: delete_character
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
      x-openapi-router-controller: swagger_server.controllers.character_controller
components:
  schemas:
    Character:
      title: Character
      required:
      - birth_year
      - eye_color
      - hair_color
      - height
      - mass
      - name
      - skin_color
      type: object
      properties:
        id:
          type: integer
          format: int32
        height:
          type: integer
          format: int32
        mass:
          type: integer
          format: int32
        birth_year:
          type: integer
          format: int32
        name:
          type: string
        hair_color:
          type: string
        skin_color:
          type: string
        eye_color:
          type: string
      example:
        eye_color: eye_color
        skin_color: skin_color
        mass: 1
        name: name
        id: 0
        height: 6
        birth_year: 5
        hair_color: hair_color
    CharacterList:
      type: array
      items:
        $ref: '#/components/schemas/Character'
      example:
      - eye_color: eye_color
        skin_color: skin_color
        mass: 1
        name: name
        id: 0
        height: 6
        birth_year: 5
        hair_color: hair_color

